branch-defaults:
  test_aws:
    environment: Gorrabot-dev
environment-defaults:
  Gorrabot-dev:
    branch: master
    repository:
global:
  application_name: Gorrabot
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
